### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by marflow** [engram-design/ExpandedSingles#1]
Hi Josh,
Thanks for sharing this plugin! Would like to use it but I get
```
Fatal error: Call to a member function getCpEditUrl() on null in /Applications/MAMP/htdocs/studio/craft/plugins/expandedsingles/ExpandedSinglesPlugin.php on line 58
```
Is this a general problem (Craft 2.3.2644) or is it because I try to use it with primary locale set to German? 
Thank you!

**Comment by engram-design** [comment]
@marflow would you like to try the latest version out? Do you have any Singles defined yet?

**Comment by marflow** [comment]
Hey Josh,
sorry for not replying earlier – busy day.
The answers to your questions: Yes. Yes. And yes, the new version is working great!
Thanks again for sharing!

**Comment by engram-design** [comment]
Not a problem - glad it's working for you now! :)
