### ISSUE TITLE
Fails on install if Redactor isn't installed

### ISSUE THREAD

**Issue by sjenset** [engram-design/ExpandedSingles#10]
### Description

Tried installing this on a clean Craft3 installation. As there's no check to see if Redactor is installed before latching onto the Redactor-hook, the installation fails

### Steps to reproduce

1. Do a clean Craft install
2. Attempt to install this plugin

### Additional info

`vendor/verbb/expanded-singles/src/ExpandedSingles.php` line 63
`Class 'craft\redactor\Field' not found`

- Plugin version: 1.0.2
- Craft version: 3.0.0-RC10.1

**Comment by engram-design** [comment]
Sorry about that, should be fixed in the [1.0.3](https://github.com/verbb/expanded-singles/releases/tag/1.0.3) version.
