### ISSUE TITLE
createSectionedSinglesList fails if a user can’t access available singles

### ISSUE THREAD

**Issue by ockam** [engram-design/ExpandedSingles#12]
### Description

When logged in as a user who can only edit some pages/sections and can’t access some singles, expanded-singles throws an error when registering the event for Redactor:

`Undefined variable: singles` at line 96 of services/SinglesList.php

The error is easily corrected by initialiasing `$singles` as an empty array before the loop (line 82).

### Additional info

- Plugin version: 1.0.3
- Craft version: 3.0.12

**Comment by ockam** [comment]
By the way, this raise an interesting concern: should a user be able to link to entries he can’t edit?

It depends on project/context, so this should probably be a setting.

**Comment by engram-design** [comment]
Fixed in [1.0.4](https://github.com/verbb/expanded-singles/releases/tag/1.0.4)
