### ISSUE TITLE
Single does not show correctly in a multisite installation when not enable for all Sites

### ISSUE THREAD

**Issue by bzin** [engram-design/ExpandedSingles#14]
### Description

So I am using Expanded Singles to organise special pages on a multisite installation. However there are  pages that only exists on a specific Site. Having creating a Single and enabled it only for one this page does not show in the sidebar and it is only visible in the `All entries` area when this site is selected.

### Steps to reproduce

1. Create a new single in a multi site installation
2. Enable this only for one site
3. Single is only visible on All Entries

### Additional info

- Plugin version: 1.0.4
- Craft version: Craft Pro 3.0.27.1

**Comment by engram-design** [comment]
Fixed in [1.0.5](https://github.com/verbb/expanded-singles/releases/tag/1.0.5)
