### ISSUE TITLE
Plugin doesn't work for non admin users in Craft 3.1

### ISSUE THREAD

**Issue by ruudvdboom** [engram-design/ExpandedSingles#15]
### Description
The plugin doesn't work for non admin users. The singles don't appear in the left menu.

### Steps to reproduce

1. create a control panel user with rights to some singles.
2. The singles don't appear in the left menu
3. I do have changed the order of the left menu.
4. The admin user is working fine
5. When i change the user to an admin user it works fine.

### Additional info

- Plugin version: 1.0.5
- Craft version: 3.1.1

**Comment by engram-design** [comment]
Should be fixed in [1.0.6](https://github.com/verbb/expanded-singles/releases/tag/1.0.6).
