### ISSUE TITLE
Service JS is injected on public site template

### ISSUE THREAD

**Issue by ockam** [engram-design/ExpandedSingles#16]
### Description
In the createSinglesList method of SinglesList class, a script is injected in the page to manage the CP sidebar.

In Craft 3.1, this script is also injected on public page. I have checked older 3.0 install and it’s not there.

This has no side effect (in my case), but generate an unnecessary request for jQuery.

### Additional info

- Plugin version: 1.0.6
- Craft version: 3.1.3

**Comment by engram-design** [comment]
Should be fixed in https://github.com/verbb/expanded-singles/releases/tag/1.0.7
