### ISSUE TITLE
Redirect to Entry will redirect to wrong site/locale

### ISSUE THREAD

**Issue by jurriaanr** [engram-design/ExpandedSingles#18]
### Description
When turning on the "Redirect to Entry" option, the entry that is redirected to is the locale of the topmost site/locale, instead of the one that is selected in the entries overview

### Steps to reproduce

1. create multiple sites
2. Select a site other than the top one in the entries overview
3. click on a single while the setting is enabled

### Additional info

- Plugin version: 1.0.7
- Craft version: 3.1

**Comment by engram-design** [comment]
This is now fixed in [1.0.8](https://github.com/verbb/expanded-singles/releases/tag/1.0.8)
