### ISSUE TITLE
Singles not hidden when switching between sites

### ISSUE THREAD

**Issue by dgtlcrftrs** [engram-design/ExpandedSingles#19]
### Description

The single pages are incorrectly shown / hidden when switching between multi-sites, for example a single page that is meant to be on Site A but not Site B. This will show on load of the entries (for site A - which is correct) but when switching (to Site B), it doesn't hide the section / single page. Refreshing (on Site B's entries) will show the correct menu structure and have them hidden accordingly. When switching back to Site A, it doesn't show the singles that are supposed to be available but were correctly hidden on Site B.

### Steps to reproduce

1. Create multi site (in two different multi-site groups) 
2. Create a single page which has it turned on for one site and switched off for the other
3. Add a new heading under the cog wheel for the entries view, and put the single under it
4. Refresh and switch between the two sites
5. you'll notice the single doesn't disappear / appear correctly unless refreshed

### Additional info

- Plugin version: 1.0.7
- Craft version: Craft Pro 3.2.10

**Comment by dgtlcrftrs** [comment]
I had a look at the code to try and figure this out, I have managed to find the issue. 

This only occurs when redirectToEntry is set to true. The JS replaces the generated A tag for the site.

**Comment by engram-design** [comment]
Yep, aware of this. Its mostly because with `redirectToEntry` set to true, it injects some JS into the page that redirects to the entry's edit page. The issue here is that the current site in the dropdown menu at the top of the page is also done through JS, but its not available at the time when we inject our content into the links to redirect off.

Will give it some further thought.

**Comment by engram-design** [comment]
Fixed in [1.0.8](https://github.com/verbb/expanded-singles/releases/tag/1.0.8)
