### ISSUE TITLE
Disabled single not appearing in nav

### ISSUE THREAD

**Issue by lindseydiloreto** [engram-design/ExpandedSingles#2]
If a Single is disabled, it won't appear in the expanded list.

Is this expected behavior?

**Comment by engram-design** [comment]
Excellent point, while it is expected behaviour, once you do that, there's no way to edit your disabled single now.

This has now been resolved in [0.2.3 release](https://github.com/engram-design/ExpandedSingles/releases/tag/0.2.3).

**Comment by lindseydiloreto** [comment]
Awesome, thanks man!
