### ISSUE TITLE
Unable to select a single that is not activated for default site in redactor link modal

### ISSUE THREAD

**Issue by nettum** [engram-design/ExpandedSingles#21]
### Description
I'm unable to link to a single page from the redactor link modal when the single is not activated for the default site.  

Somewhat related to #18 and #19 because of multisite, but I've been able to dodge these two by disabling "Redirect to Entry" option. This bug however seems to be present no matter if "Redirect to Entry" is enabled or not.

### Steps to reproduce

1. Install craft, redactor and expanded-singles.
2. Add a secondary site (SiteB)
![image](https://user-images.githubusercontent.com/798156/73738652-235f8700-4745-11ea-9661-986da7bbeb04.png)  

3.Setup a single that is enabled for both sites.
![image](https://user-images.githubusercontent.com/798156/73738757-56a21600-4745-11ea-9eab-76fe8bad370a.png)

4. Setup a single that is *only* enabled for the secondary site (SiteB)
![image](https://user-images.githubusercontent.com/798156/73738801-6ae61300-4745-11ea-85fc-4102efb3e693.png)

5. Add a channel and add a redactor field to the channel entry types
![image](https://user-images.githubusercontent.com/798156/73739452-830a6200-4746-11ea-8331-6153aae441f1.png)  
![image](https://user-images.githubusercontent.com/798156/73739503-9f0e0380-4746-11ea-8a92-05475f606a89.png)

6. Create and entry in the newly created channel on SiteB and use the "Link to an entry" in the redactor field
![image](https://user-images.githubusercontent.com/798156/73740159-e943b480-4747-11ea-914f-958cfedd4ccf.png)

7. I can only choose "SingleAandB", not "SingleB".
![image](https://user-images.githubusercontent.com/798156/73740249-214af780-4748-11ea-8e4d-20b0978faba0.png)

8. If I disable expanded-singles I see both singles when using "Link to an entry"
![image](https://user-images.githubusercontent.com/798156/73740307-3de72f80-4748-11ea-81af-64293c1acd67.png)

### Additional info

- Plugin version: 1.0.7
- Craft version: Tested on both 3.4.3 and 3.3.18.2

**Comment by engram-design** [comment]
Fixed in [1.0.8](https://github.com/verbb/expanded-singles/releases/tag/1.0.8)

**Comment by nettum** [comment]
Awesome Josh!   
Just updated the test project and everything seems to work nicely now! :tada:
