### ISSUE TITLE
Doesn't redirect to Entry anymore

### ISSUE THREAD

**Issue by romainpoirier** [engram-design/ExpandedSingles#24]
### Description

The plugin doesn't redirect to Entry anymore, even with `Redirect to Entry` and `Expand Singles` options enabled.

With `Expand Singles` option enabled, the Singles link is added to the list, but clicking it doesn't redirect to Entry: it redirects to a single-item list where you have to click again to show the Entry.

I think this is not the expected behaviour, and that's not how it worked previously.

In this example, _Page d'accueil_ is a Single: clicking on its link should redirect straight to the last screen:
![screencast](https://user-images.githubusercontent.com/4634192/75441876-bcf21100-595e-11ea-8424-e298bd939a8d.gif)

### Steps to reproduce

1. Enable `Expand Singles` + `Redirect to Entry`
2. Visit `/admin/entries`, click on the Single link

### Additional info

- Plugin version: 1.0.9
- Craft version: Craft Pro 3.4.8

**Comment by engram-design** [comment]
Behaviour was changed in 1.0.9, but it should've improved things. Can you clear your caches, and check if there are any Javascript errors in your web console?

**Comment by engram-design** [comment]
You might also like to check [1.0.10](https://github.com/verbb/expanded-singles/releases/tag/1.0.10) with some debugging statements added in the console, and a little bit of a refactor with the JS.

**Comment by romainpoirier** [comment]
After upgrading to 1.0.10, I can still says that this issue is not fixed.

After clearing my browser cache, below is the only output I can see now in the console (after clicking on the Single link on the Entries navbar):
`Expanded Singles: `

The `Redirect to Entry` option has still not effect for me.

**Comment by engram-design** [comment]
@romainpoirier Would you be able to send a screenshot of the inspected element, similar to the below? I'm interested in the outputted HTML.

<img width="835" alt="Screen Shot 2020-02-28 at 8 23 58 pm" src="https://user-images.githubusercontent.com/1221575/75531879-4b05ee80-5a68-11ea-9dea-df149f7b7088.png">

**Comment by romainpoirier** [comment]
Yep:
![expanded-single-screenshot-source-code](https://user-images.githubusercontent.com/4634192/75538889-a5c42980-5a19-11ea-9e79-abf20c6e0f8c.png)

**Comment by engram-design** [comment]
Would you be able to give [1.0.11](https://github.com/verbb/expanded-singles/releases/tag/1.0.11) a go? Is the French site also your primary site? What site ID is it?

**Comment by romainpoirier** [comment]
Yes, the French site is also my primary site, which site ID is `1` (handle: `fr`).

I was not able to upgrade to `"verbb/expanded-singles": "1.0.11"`:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package verbb/expanded-singles 1.0.11 exists as verbb/expanded-singles[1.0.0, 1.0.1, 1.0.10, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9, dev-craft-3] but these are rejected by your constraint.
```

**Comment by engram-design** [comment]
Hmm, might take a minute or two for the version to propagate on Packagist - give it a minute or two and try again.

**Comment by romainpoirier** [comment]
Thank you, I was able to upgrade, and I can confirm this is now working as expected :)

**Comment by engram-design** [comment]
Great to hear, and thanks for your patience with helping fix this!

**Comment by itsmattsoria** [comment]
Adding to this — I'm also working in a multi-site environment and while in the primary site the redirection works, but when on any of the other non-primary sites the redirection does not work, it just pulls up the entry in the right-hand panel as would be normal otherwise. Here's a screenshot of inspecting it from the non-primary site (which has the handle `bv` and a siteID of `2`):

![](https://share.mattsoria.com/Screen-Shot-2021-08-28-14-25-21.jpg)

I'm on plugin version 1.1.4 and Craft version 3.7.10
