### ISSUE TITLE
Duplicate link to entry in Craft 3.5RC1

### ISSUE THREAD

**Issue by daltonrooney** [engram-design/ExpandedSingles#28]
### Description
I have one single, called Homepage, and both "Expand Singles" and "Redirect to Entry" enabled. This creates a duplicate entry in the entries list, one of which uses the default Singles behavior and one which uses the Expanded Singles behavior. I don't recall seeing this in any of the 3.5 betas previously.

![Screen Shot 2020-07-22 at 2 41 46 PM](https://user-images.githubusercontent.com/742045/88231683-7b257800-cc29-11ea-8382-1bc45cf6080c.png)

### Steps to reproduce

1. Upgrade to Craft 3.5RC1
2. Enable "Expand Singles" and "Redirect to Entry" in the Expanded Singles settings page.

### Additional info

- Plugin version: 1.12
- Craft version: 3.5RC1

**Comment by engram-design** [comment]
Should be fixed in [1.1.3](https://github.com/verbb/expanded-singles/releases/tag/1.1.3)
