### ISSUE TITLE
Failure to redirect to home page currentSite

### ISSUE THREAD

**Issue by JSDigital-Jeff** [engram-design/ExpandedSingles#29]
**Description**
What we have is a system in which the default website is us.
We have a separate website 'Website B' with a user that is only allowed to view and edit 'Website B'.

Although when the user clicks on 'Home' (which is a single) it wants to direct the user to the home single page of the 'Default' website to which it has no permissions resulting in a permission denial error. 

If the user of 'Website B' clicks on home it should direct to the homepage of 'Website B' and not to 'Default'.

**Steps to reproduce**
1. Have the plugin installed
2. Have two different sites
3. Have a user which is only permitted to view and edit the non-default website
4. Let both sites have a home single 
5. As the user of the non-default site click on the home page underneath singles
6. Be denied permission as you see that in the URL bar it directed to the default site instead of the non-default site

**Additional info**
- Plugin version: 1.1.4
- Craft version: 3.7.26
- Multi-site: Yes

**Comment by engram-design** [comment]
Should be fixed in [1.1.5](https://github.com/verbb/expanded-singles/releases/tag/1.1.5)
