### ISSUE TITLE
Craft.cp.getSiteId is not a function until Craft 3.5

### ISSUE THREAD

**Issue by bgrrtt** [engram-design/ExpandedSingles#30]
**Description**

The redirectToEntry functionality is broken unless on Craft 3.5+. 

https://github.com/verbb/expanded-singles/releases/tag/1.1.5 requires Craft ^3.5.0.

https://github.com/craftcms/cms/blob/develop/CHANGELOG.md#350---2020-08-04

> - Added the `Craft.cp.getSiteId()` and `setSiteId()` JavaScript methods.

**Steps to reproduce**
1. Update to 1.1.5 from 1.1.4 on Craft 3.4
2. Click on a Single in Entries
3. See the following in the Browser Inspector's console:

```
Uncaught TypeError: Craft.cp.getSiteId is not a function
    at expanded-singles.js?v=1646167213:1:79
    at expanded-singles.js?v=1646167213:1:809
```

**Additional info**
- Plugin version: 1.1.5
- Craft version: 3.4
- Multi-site: No

**Additional context**

- Pinning the Plugin version 1.1.4 restores functionality.

**Comment by engram-design** [comment]
Ah, that's frustrating, didn't even realise that was a newer function. Fixed in [1.1.6](https://github.com/verbb/expanded-singles/releases/tag/1.1.6) and bumped the original fix to [1.2.0](https://github.com/verbb/expanded-singles/releases/tag/1.2.0) which requires Craft 3.5+.
