### ISSUE TITLE
[Craft 4] Other user groups not seeing the singles

### ISSUE THREAD

**Issue by carolineboeykens** [engram-design/ExpandedSingles#31]
**Description**
We updated to Craft 4 and also this plugin to 2.0.0-beta.1, and it is working for the admin user. But the other users (who have also permissions to the sections and singles) do not see the singles in the side bar.

![Screenshot 2022-05-13 at 08 40 31](https://user-images.githubusercontent.com/42932673/168226231-9633e675-2458-4d46-8198-6d1a5835584a.png)

Left is admin, right is content manager user group.

Can you take a look at this?

**Steps to reproduce**
1. Create a user group with permissions to entries and singles
2. Update to Craft 4
3. Update Expanded Singles to 2.0.0-beta.1
4. Login as a user (not admin)

**Additional info**
- Plugin version: 2.0.0-beta.1
- Craft version: 4.0.2
- Multi-site: Yes

**Comment by engram-design** [comment]
Should be fixed for the next release. Run `composer require verbb/expanded-singles:dev-craft-4` to get it early.

**Comment by engram-design** [comment]
Fixed in [2.0.0](https://github.com/verbb/expanded-singles/releases/tag/2.0.0)
