### ISSUE TITLE
Craft 4.4

### ISSUE THREAD

**Issue by srosenbrand** [engram-design/ExpandedSingles#32]
### Describe the bug

Selecting singles from an entry field or from redactor isn't possible anymore in Craft 4.4. You can click the single section in the left bar, but can't select the actual single because it is hidden/not shown. Also, in the general entries section, if you click on a single it will redirect, but if you go back the actual entry is not visible.

This behavior makes it impossible to create links to single entries.

### Steps to reproduce

1. 
2. 

### Craft CMS version

4.4

### Plugin version

2.0.0

### Multi-site?

Yes

**Comment by engram-design** [comment]
Should be fixed in [2.0.1](https://github.com/verbb/expanded-singles/releases/tag/2.0.1)
