### ISSUE TITLE
Singles aren't visible in entry selection modal via CKEditor link option

### ISSUE THREAD

**Issue by mikesnoeren** [engram-design/ExpandedSingles#33]
### Describe the bug

When making an inline link that links to an entry using the new CKEditor, it's not possible to select any of the singles as they are excluded from the modal sidebar. 

Unsure if this is an issue with the `CKEditor` plugin or with the `expanded singles` plugin. 
Please let me know if I am in the wrong place!

### Steps to reproduce

1. Make a CKEditor field with link option enabled.
2. Create a link, link it to a single.
3. Find out the singles are missing from the entry pick modal.

### Craft CMS version

4.4.14

### Plugin version

2.0.1

### Multi-site?

No

**Comment by engram-design** [comment]
Likely us needing to add support for this, like we do [with Redactor](https://github.com/verbb/expanded-singles/blob/976f7f150e6468a0dc6b96a53570146144166207/src/ExpandedSingles.php#L72).

Added for the next release. To get this early run `composer require verbb/expanded-singles:"dev-craft-4 as 2.0.1"`

**Comment by engram-design** [comment]
Added in [2.0.2](https://github.com/verbb/expanded-singles/releases/tag/2.0.2)
