### ISSUE TITLE
Disabled singles not visible in 2.0.3

### ISSUE THREAD

**Issue by janhenckens** [engram-design/ExpandedSingles#37]
### Describe the bug

After updating to 2.0.3, single entries that are disabled aren't shown in the sidebar anymore

### Steps to reproduce

1. disable a single
2. update to 2.0.3

### Craft CMS version

4.4.15

### Plugin version

2.0.3

### Multi-site?

Yes

### Additional context

Submitted https://github.com/verbb/expanded-singles/pull/36 with a fix for this.

**Comment by engram-design** [comment]
Fixed in [2.0.4](https://github.com/verbb/expanded-singles/releases/tag/2.0.4). Thanks again!

**Comment by janhenckens** [comment]
Thanks @engram-design!
