### ISSUE TITLE
Singles not showing in a multi websites

### ISSUE THREAD

**Issue by carolineboeykens** [engram-design/ExpandedSingles#38]
### Describe the bug

We have multiple subsites in one backend and the singles are only showing in the default website.
If I downgrade to 2.0.2 it is working again.

### Steps to reproduce

1. Update to 2.0.4
2. Have a multi site

### Craft CMS version

4.4.16.1

### Plugin version

2.0.4

### Multi-site?

Yes

**Comment by engram-design** [comment]
Fixed in [2.0.5](https://github.com/verbb/expanded-singles/releases/tag/2.0.5)
