### ISSUE TITLE
Not working with multiple language 

### ISSUE THREAD

**Issue by duur222** [engram-design/ExpandedSingles#4]
When there are 2 or more locale installed the plugin doesn't work for the other locale.

I have added this line to ExpandedSinglesPlugin.php (line 38) to make it work for me:
`$criteria->locale = craft()->i18n->getPrimarySiteLocale()->id;`

**Comment by engram-design** [comment]
Well picked up, fixed in the [latest master](https://github.com/engram-design/ExpandedSingles/archive/master.zip).
