### ISSUE TITLE
Single not selectable as related entry

### ISSUE THREAD

**Issue by ray-001** [engram-design/ExpandedSingles#8]
### Description
When trying to attach the single as a related entry I get an error, An unknown error occurred.
Looking at the web.log I found that there's something wrong with the permissions.

> 2018-02-01 17:33:31 [::1][1][bhvpq797nia4u0tudjvbf8r787][error][yii\web\HttpException:403] yii\web\ForbiddenHttpException: User not permitted to access this source in /Users/someuser/Projects/myproject/vendor/craftcms/cms/src/controllers/ElementIndexesController.php:265

### Steps to reproduce

1. Create entry field with singles enabled.
2. Attach entry field to section.
3. Try to select a single.

### Additional info

- Plugin version: 1.0.1
- Craft version: Craft Pro 3.0.0-RC8

**Comment by engram-design** [comment]
@ray-001 This should be fixed in the latest master (use `composer require verbb/expanded-singles:dev-craft-3` to update), and will be rolled into the next release.

**Comment by ray-001** [comment]
Thank you!
