### ISSUE TITLE
Error when using field type content

### ISSUE THREAD

**Issue by KevinBeckers** [engram-design/ExpandedSingles#9]
### Description
Select content inside field type content doesnt resolve in selecting the entry.

### Steps to reproduce
1. Create a field with field type content
2. Try to pick an entry from in that field.

### Additional info

- Plugin version: Latest
- Craft version: Latest

**Comment by engram-design** [comment]
See the latest release https://github.com/verbb/expanded-singles/releases/tag/1.0.2 for this fix. Referenced https://github.com/verbb/expanded-singles/issues/8
